### ISSUE TITLE
[RFC] Expansion Pack

### ISSUE THREAD

**Issue by theodorusclarence** [theodorusclarence/ts-nextjs-tailwind-starter#55]
With the expansion pack, we can install dependencies and all of the configs just by a bash command.

https://user-images.githubusercontent.com/55318172/145711215-ace4c07f-32ef-40ee-9d71-fd83e251f528.mp4

It will be managed on a separate repository https://github.com/theodorusclarence/expansion-pack

### Roadmap

- [x] React Hook Form + Form Input Components
- [x] Storybook
- [x] Cypress
- [ ] Authentication with Zustand
- [x] [Toast with SWR](https://theodorusclarence.com/blog/react-loading-state-pattern)
- [x] [Dialog Manager with Zustand](https://github.com/theodorusclarence/dialog-manager)

That is the roadmap that I got in mind with some example repo I have made. If you have something you want to add and contribute, comment below!
